// Generated by sixpack. Do not edit by hand.
import { createTable, type SixpackSchema } from "@sixpack/db";

export interface UsersRow {
  readonly id: string;
  readonly name: string;
  readonly email: string;
  readonly is_ai_user: boolean;
}

export const users = createTable<UsersRow>()({
  name: "users",
  fields: {
    id: "id",
    name: "text",
    email: "text",
    is_ai_user: "bool",
  },
  lookups: {
    id: { kind: "id", unique: true },
    email: { kind: "text", unique: true },
  },
});

export interface ConversationsRow {
  readonly id: string;
  readonly owner_id: string;
  readonly title: string;
  readonly created_at: bigint;
}

export const conversations = createTable<ConversationsRow>()({
  name: "conversations",
  fields: {
    id: "id",
    owner_id: "id",
    title: "text",
    created_at: "int",
  },
  lookups: {
    id: { kind: "id", unique: true },
    owner_id: { kind: "id", unique: false },
    created_at: { kind: "int", unique: false },
  },
});

export interface MessagesRow {
  readonly id: string;
  readonly conversation_id: string;
  readonly sender_id: string;
  readonly body: string;
  readonly created_at: bigint;
}

export const messages = createTable<MessagesRow>()({
  name: "messages",
  fields: {
    id: "id",
    conversation_id: "id",
    sender_id: "id",
    body: "text",
    created_at: "int",
  },
  lookups: {
    id: { kind: "id", unique: true },
    conversation_id: { kind: "id", unique: false },
    created_at: { kind: "int", unique: false },
  },
});

export const schema = {
  hash: "0998dc171e3b836c",
  tables: {
    users,
    conversations,
    messages,
  },
} satisfies SixpackSchema;
